# Generated by Django 4.1 on 2022-09-07 05:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(help_text="최대 20자로 작성 해주세요", max_length=10)),
                (
                    "content",
                    models.TextField(help_text="최대 200자로 작성 해주세요", max_length=200),
                ),
                (
                    "author",
                    models.CharField(help_text="최대 20자로 작성 해주세요", max_length=10),
                ),
                (
                    "password",
                    models.CharField(
                        default=None,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.MinLengthValidator(6, "6자 이상 적어주세요")
                        ],
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
    ]
